### ISSUE TITLE
Unspecified license

### ISSUE THREAD

**Issue by capeterson** [codehutch/sIndent#3]
Hi, I noticed your project doesn't include a LICENSE file. I've seen a few people talking about possibly integrating it into other systems, like a Chrome extension, so there's certainly interest in this project. 

I'd love to see a BSD or MIT license on this project, if you're comfortable with it of course, as it might lead to some potentially very useful derivative works. 

Thanks for considering it!

**Comment by afawcett** [comment]
:+1:

**Comment by codehutch** [comment]
ok, no problem. Please consider it MIT licensed. I'll try to work out how to do it properly...

**Comment by codehutch** [comment]
I've updated the readme too. Let me know if I should do something else. Ta. Hope it's useful.
